name 'casa-on-rails'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'apachev2'
description 'Installs/Configures casa-on-rails'
long_description 'Installs/Configures casa-on-rails'
version '0.5.3'
